<?php
/**
 * @file
 * energy_council_work_streams.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function energy_council_work_streams_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_council_priority_issue'
  $field_bases['field_council_priority_issue'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_council_priority_issue',
    'indexes' => array(
      'tid' => array(
        0 => 'tid',
      ),
    ),
    'locked' => 0,
    'module' => 'taxonomy',
    'settings' => array(
      'allowed_values' => array(
        0 => array(
          'vocabulary' => 'priority_issues_of_national_significance',
          'parent' => 0,
        ),
      ),
    ),
    'translatable' => 0,
    'type' => 'taxonomy_term_reference',
  );

  // Exported field_base: 'field_related_documents'
  $field_bases['field_related_documents'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_related_documents',
    'indexes' => array(
      'nid' => array(
        0 => 'nid',
      ),
    ),
    'locked' => 0,
    'module' => 'node_reference',
    'settings' => array(
      'referenceable_types' => array(
        'article' => 0,
        'consultation' => 0,
        'event' => 0,
        'news' => 0,
        'page' => 0,
        'publications' => 'publications',
        'work_stream' => 0,
      ),
      'view' => array(
        'args' => array(),
        'display_name' => '',
        'view_name' => '',
      ),
    ),
    'translatable' => 0,
    'type' => 'node_reference',
  );

  return $field_bases;
}
