<?php
/**
 * @file
 * energy_council_news_list.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function energy_council_news_list_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function energy_council_news_list_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}
