<?php 
/** 
* Implements hook_block_info(). 
*/ 

function energy_council_mailchimp_block_info() { 
	$block['energy_council_subscribe'] = array(
		'info' => t('Subscription Form'),
		'cache' => DRUPAL_NO_CACHE, );
	return $block;
}
/** 
* Implements hook_block_view(). 
*/

function energy_council_mailchimp_block_view($block_key) {
	$block = array();
	if($block_key == 'energy_council_subscribe')
	{ 
		$block['subject'] = t('Subscription Form'); 
		$block['content'] = 
		'<!-- Begin MailChimp Signup Form -->
		<div id="mc_embed_signup">
			<form action="//industry.us11.list-manage.com/subscribe/post?u=8ed6f6a545e71ff832ce3e1af&amp;id=cee3d014e7" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
				<div id="mc_embed_signup_scroll">
					<p>If you would like to receive updates about COAG Energy Council, simply subscribe below.</p>
					<div class="indicates-required">
						<p><span class="asterisk">*</span> indicates required field</p>
					</div>
					<div class="mc-field-group form-item">
						<label for="mce-EMAIL">Email Address <span class="asterisk">*</span> </label>
						<input class="required email" id="mce-EMAIL" name="EMAIL" type="email" value="" />
					</div>
					<div class="mc-field-group form-item">
						<label for="mce-NAME">Name <span class="asterisk">*</span> </label>
						<input class="required" id="mce-NAME" name="NAME" type="text" value="" />
					</div>
					<div class="clear" id="mce-responses">
						<div class="response" id="mce-error-response" style="display:none">&nbsp;</div>
						<div class="response" id="mce-success-response" style="display:none">&nbsp;</div>
					</div>
					<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
					<div style="position: absolute; left: -5000px;">
						<input name="b_8ed6f6a545e71ff832ce3e1af_cee3d014e7" tabindex="-1" type="text" value="" />
					</div>
					<div class="clear">
						<input class="button form-submit" id="mc-embedded-subscribe" name="subscribe" type="submit" value="Subscribe" />
					</div>
				</div>
			</form>
		</div>
		<script type=\'text/javascript\' src=\'//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js\'></script>
		<script type=\'text/javascript\'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]=\'EMAIL\';ftypes[0]=\'email\';fnames[2]=\'NAME\';ftypes[2]=\'text\';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
		<!--End mc_embed_signup-->'; 
	} 
	return $block;
} 