<?php

/**
 * Implements hook_help().
 */
function industry_events_help($path, $arg) {
  switch ($path) {
    case 'admin/help#industry_events':
      $output = file_get_contents(drupal_get_path('module', 'industry_events') . '/README.txt');
      return module_exists('markdown') ? filter_xss_admin(module_invoke('markdown', 'filter', 'process', 0, -1, $output)) : '<pre>' . check_plain($output) . '</pre>';
  }
}

/**
 * @file
 * Code for the Events feature.
 */

include_once 'industry_events.features.inc';
